name: CI  Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.15.0'

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build the React app
      run: |
        cd app
        npm run build

    # - name: Log in to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1
    #   with:
    #     region: ${{ secrets.AWS_REGION }}

    # - name: Build, tag, and push Docker image
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: your-ecr-repository-name
    #     IMAGE_TAG: ${{ github.sha }}
    #   run: |
    #     cd frontend
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # - name: Deploy to a server (optional)
    #   run: |
    #     # Your deployment script here, e.g., using ssh and scp to transfer the Docker image or other deployment steps
    #     echo "Deploying to server"
